# Generated by Django 4.0.5 on 2022-07-04 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name of group')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
        ),
        migrations.CreateModel(
            name='PrimaryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name of group')),
            ],
            options={
                'verbose_name': 'Primary Group',
                'verbose_name_plural': 'Primary Groups',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'voucher',
                'verbose_name_plural': 'vouchers',
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name of Ledger')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('opening', models.IntegerField(blank=True, null=True, verbose_name='Opening Balance')),
                ('under', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group', verbose_name='Under')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ledger',
                'verbose_name_plural': 'ledgers',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('sn', models.CharField(blank=True, max_length=50, null=True, verbose_name='Voucher No.')),
                ('rn', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference No.')),
                ('nar', models.TextField(blank=True, null=True, verbose_name='Narration')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='Amount')),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='by', to='core.ledger', verbose_name='By')),
                ('to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.ledger', verbose_name='To')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.voucher', verbose_name='Voucher Type')),
            ],
            options={
                'verbose_name': 'journal',
                'verbose_name_plural': 'journal',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='under',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.primarygroup', verbose_name='Under'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Legal name')),
                ('address', models.TextField(verbose_name='Address')),
                ('city', models.CharField(max_length=200, verbose_name='City')),
                ('state', models.CharField(max_length=200, verbose_name='State')),
                ('country', models.CharField(max_length=200, verbose_name='Country')),
                ('pincode', models.CharField(max_length=50, verbose_name='Pincode')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone no.')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.CharField(max_length=250, verbose_name='Website')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companys',
            },
        ),
    ]
